# Generated by Django 6.0 on 2026-04-02 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FunnelStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('button_text', models.CharField(max_length=200)),
                ('button_url', models.URLField(blank=True, help_text='URL for the button (e.g., /clarity-50/)')),
                ('step_type', models.CharField(choices=[('clarity', 'Clarity Entry'), ('challenge', 'Challenge'), ('conversion', 'Conversion')], default='clarity', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
