# Generated by Django 6.0 on 2026-04-02 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_funnelstep'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAdvantagePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='AI Fear vs AI Advantage', max_length=200)),
                ('subtitle', models.CharField(default='AI is not replacing people — it is empowering those who learn how to use it.', max_length=300)),
                ('description', models.TextField(default='We are living in a powerful technological shift. Many people fear that artificial intelligence will replace them, while others are learning how to use it as a tool to grow faster. The difference is not intelligence or talent — it is clarity and direction.')),
                ('image', models.ImageField(help_text='Main image for the AI Advantage section', upload_to='ai_advantage/')),
                ('video_title', models.CharField(default='Who Controls AI?', max_length=200)),
                ('video_thumbnail', models.ImageField(help_text='Video thumbnail image', upload_to='ai_advantage/thumbnails/')),
                ('video_type', models.CharField(choices=[('youtube', 'YouTube Link'), ('upload', 'Upload Video')], default='youtube', max_length=10)),
                ('youtube_url', models.URLField(blank=True, help_text='YouTube video URL (e.g., https://www.youtube.com/watch?v=...)')),
                ('uploaded_video', models.FileField(blank=True, help_text='Upload video file if not using YouTube', null=True, upload_to='ai_advantage/videos/')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI Advantage Page',
                'verbose_name_plural': 'AI Advantage Page',
            },
        ),
    ]
