# Generated by Django 6.0 on 2026-04-03 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_aiadvantagepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillTestPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Skill Test', max_length=200)),
                ('subtitle', models.CharField(default='Test your skills and knowledge', max_length=300)),
                ('description', models.TextField(default='Assess your abilities and understand where you stand.')),
                ('image', models.ImageField(help_text='Main image for the Skill Test section', upload_to='skill_test/')),
                ('video_title', models.CharField(default='Watch Now', max_length=200)),
                ('video_thumbnail', models.ImageField(help_text='Video thumbnail image', upload_to='skill_test/thumbnails/')),
                ('video_type', models.CharField(choices=[('youtube', 'YouTube Link'), ('upload', 'Upload Video')], default='youtube', max_length=10)),
                ('youtube_url', models.URLField(blank=True, help_text='YouTube video URL')),
                ('uploaded_video', models.FileField(blank=True, help_text='Upload video file if not using YouTube', null=True, upload_to='skill_test/videos/')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Skill Test Page',
                'verbose_name_plural': 'Skill Test Page',
            },
        ),
    ]
