# Generated by Django 6.0 on 2026-04-03 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_learningsystempage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerRoadmapPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Career Roadmap', max_length=200)),
                ('subtitle', models.CharField(default='Every successful career begins with a clear path', max_length=300)),
                ('description', models.TextField(default='This roadmap provides a simple and structured journey from zero knowledge to industry readiness.')),
                ('image', models.ImageField(help_text='Main image for the Career Roadmap section', upload_to='career_roadmap/')),
                ('video_title', models.CharField(default='Watch Now', max_length=200)),
                ('video_thumbnail', models.ImageField(help_text='Video thumbnail image', upload_to='career_roadmap/thumbnails/')),
                ('video_type', models.CharField(choices=[('youtube', 'YouTube Link'), ('upload', 'Upload Video')], default='youtube', max_length=10)),
                ('youtube_url', models.URLField(blank=True, help_text='YouTube video URL')),
                ('uploaded_video', models.FileField(blank=True, help_text='Upload video file if not using YouTube', null=True, upload_to='career_roadmap/videos/')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Career Roadmap Page',
                'verbose_name_plural': 'Career Roadmap Page',
            },
        ),
    ]
