# Generated by Django 6.0 on 2026-04-03 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_careerroadmappage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerCapsulesPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Career Capsules', max_length=200)),
                ('subtitle', models.CharField(default='Short, focused career insights', max_length=300)),
                ('description', models.TextField(default='Quick lessons to boost your career growth.')),
                ('image', models.ImageField(help_text='Main image for the Career Capsules section', upload_to='career_capsules/')),
                ('video_title', models.CharField(default='Watch Now', max_length=200)),
                ('video_thumbnail', models.ImageField(help_text='Video thumbnail image', upload_to='career_capsules/thumbnails/')),
                ('video_type', models.CharField(choices=[('youtube', 'YouTube Link'), ('upload', 'Upload Video')], default='youtube', max_length=10)),
                ('youtube_url', models.URLField(blank=True, help_text='YouTube video URL')),
                ('uploaded_video', models.FileField(blank=True, help_text='Upload video file if not using YouTube', null=True, upload_to='career_capsules/videos/')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Career Capsules Page',
                'verbose_name_plural': 'Career Capsules Page',
            },
        ),
    ]
