# Generated by Django 6.0 on 2026-04-03 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_careercapsulespage'),
    ]

    operations = [
        migrations.CreateModel(
            name='LanguageBarrierPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Language Barrier', max_length=200)),
                ('subtitle', models.CharField(default='Overcome communication challenges', max_length=300)),
                ('description', models.TextField(default='Break through language barriers in your career.')),
                ('image', models.ImageField(help_text='Main image for the Language Barrier section', upload_to='language_barrier/')),
                ('video_title', models.CharField(default='Watch Now', max_length=200)),
                ('video_thumbnail', models.ImageField(help_text='Video thumbnail image', upload_to='language_barrier/thumbnails/')),
                ('video_type', models.CharField(choices=[('youtube', 'YouTube Link'), ('upload', 'Upload Video')], default='youtube', max_length=10)),
                ('youtube_url', models.URLField(blank=True, help_text='YouTube video URL')),
                ('uploaded_video', models.FileField(blank=True, help_text='Upload video file if not using YouTube', null=True, upload_to='language_barrier/videos/')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Language Barrier Page',
                'verbose_name_plural': 'Language Barrier Page',
            },
        ),
    ]
