# Generated by Django 4.2.30 on 2026-04-21 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_languagebarrierpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hero/')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Hero Image',
                'verbose_name_plural': 'Hero Image',
            },
        ),
        migrations.CreateModel(
            name='ReadyForTestPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Ready for Test', max_length=200)),
                ('subtitle', models.CharField(default='Test your readiness', max_length=300)),
                ('description', models.TextField(default="Check if you're ready for the next step.")),
                ('video_title', models.CharField(default='Watch Now', max_length=200)),
                ('video_thumbnail', models.ImageField(help_text='Video thumbnail image', upload_to='ready_for_test/thumbnails/')),
                ('video_type', models.CharField(choices=[('youtube', 'YouTube Link'), ('upload', 'Upload Video')], default='youtube', max_length=10)),
                ('youtube_url', models.URLField(blank=True, help_text='YouTube video URL')),
                ('uploaded_video', models.FileField(blank=True, help_text='Upload video file if not using YouTube', null=True, upload_to='ready_for_test/videos/')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ready For Test Page',
                'verbose_name_plural': 'Ready For Test Page',
            },
        ),
        migrations.CreateModel(
            name='TestBeforeTrustPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Test Before You Trust', max_length=200)),
                ('subtitle', models.CharField(default='Verify before you commit', max_length=300)),
                ('description', models.TextField(default='Test our system before you trust us completely.')),
                ('background_image', models.ImageField(blank=True, help_text='Background image with three Explore This Path buttons', null=True, upload_to='test_before_trust/background/')),
                ('video_1_title', models.CharField(blank=True, default='Left Video', max_length=200)),
                ('video_1_type', models.CharField(choices=[('youtube', 'YouTube Link'), ('upload', 'Upload Video')], default='youtube', max_length=10)),
                ('video_1_youtube_url', models.URLField(blank=True, default='', help_text='YouTube video URL for left button')),
                ('video_1_uploaded', models.FileField(blank=True, null=True, upload_to='test_before_trust/videos/1/')),
                ('video_2_title', models.CharField(blank=True, default='Center Video', max_length=200)),
                ('video_2_type', models.CharField(choices=[('youtube', 'YouTube Link'), ('upload', 'Upload Video')], default='youtube', max_length=10)),
                ('video_2_youtube_url', models.URLField(blank=True, default='', help_text='YouTube video URL for center button')),
                ('video_2_uploaded', models.FileField(blank=True, null=True, upload_to='test_before_trust/videos/2/')),
                ('video_3_title', models.CharField(blank=True, default='Right Video', max_length=200)),
                ('video_3_type', models.CharField(choices=[('youtube', 'YouTube Link'), ('upload', 'Upload Video')], default='youtube', max_length=10)),
                ('video_3_youtube_url', models.URLField(blank=True, default='', help_text='YouTube video URL for right button')),
                ('video_3_uploaded', models.FileField(blank=True, null=True, upload_to='test_before_trust/videos/3/')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Test Before Trust Page',
                'verbose_name_plural': 'Test Before Trust Page',
            },
        ),
        migrations.CreateModel(
            name='TopBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='banner/')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Top Banner',
                'verbose_name_plural': 'Top Banner',
            },
        ),
        migrations.DeleteModel(
            name='Slider',
        ),
        migrations.AlterModelOptions(
            name='careerroadmappage',
            options={'verbose_name': 'IT Aspirant', 'verbose_name_plural': 'IT Aspirant'},
        ),
        migrations.AlterModelOptions(
            name='languagebarrierpage',
            options={'verbose_name': '3 Career Paths', 'verbose_name_plural': '3 Career Paths'},
        ),
        migrations.AlterModelOptions(
            name='skilltestpage',
            options={'verbose_name': 'Conceptual Communication', 'verbose_name_plural': 'Conceptual Communication'},
        ),
        migrations.RemoveField(
            model_name='languagebarrierpage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='languagebarrierpage',
            name='uploaded_video',
        ),
        migrations.RemoveField(
            model_name='languagebarrierpage',
            name='video_thumbnail',
        ),
        migrations.RemoveField(
            model_name='languagebarrierpage',
            name='video_title',
        ),
        migrations.RemoveField(
            model_name='languagebarrierpage',
            name='video_type',
        ),
        migrations.RemoveField(
            model_name='languagebarrierpage',
            name='youtube_url',
        ),
        migrations.RemoveField(
            model_name='skilltestpage',
            name='image',
        ),
        migrations.AddField(
            model_name='languagebarrierpage',
            name='background_image',
            field=models.ImageField(blank=True, help_text='Background image with three Explore This Path buttons', null=True, upload_to='language_barrier/background/'),
        ),
        migrations.AddField(
            model_name='languagebarrierpage',
            name='video_1_title',
            field=models.CharField(blank=True, default='Left Video', max_length=200),
        ),
        migrations.AddField(
            model_name='languagebarrierpage',
            name='video_1_type',
            field=models.CharField(choices=[('youtube', 'YouTube Link'), ('upload', 'Upload Video')], default='youtube', max_length=10),
        ),
        migrations.AddField(
            model_name='languagebarrierpage',
            name='video_1_uploaded',
            field=models.FileField(blank=True, null=True, upload_to='language_barrier/videos/1/'),
        ),
        migrations.AddField(
            model_name='languagebarrierpage',
            name='video_1_youtube_url',
            field=models.URLField(blank=True, default='', help_text='YouTube video URL for left button'),
        ),
        migrations.AddField(
            model_name='languagebarrierpage',
            name='video_2_title',
            field=models.CharField(blank=True, default='Center Video', max_length=200),
        ),
        migrations.AddField(
            model_name='languagebarrierpage',
            name='video_2_type',
            field=models.CharField(choices=[('youtube', 'YouTube Link'), ('upload', 'Upload Video')], default='youtube', max_length=10),
        ),
        migrations.AddField(
            model_name='languagebarrierpage',
            name='video_2_uploaded',
            field=models.FileField(blank=True, null=True, upload_to='language_barrier/videos/2/'),
        ),
        migrations.AddField(
            model_name='languagebarrierpage',
            name='video_2_youtube_url',
            field=models.URLField(blank=True, default='', help_text='YouTube video URL for center button'),
        ),
        migrations.AddField(
            model_name='languagebarrierpage',
            name='video_3_title',
            field=models.CharField(blank=True, default='Right Video', max_length=200),
        ),
        migrations.AddField(
            model_name='languagebarrierpage',
            name='video_3_type',
            field=models.CharField(choices=[('youtube', 'YouTube Link'), ('upload', 'Upload Video')], default='youtube', max_length=10),
        ),
        migrations.AddField(
            model_name='languagebarrierpage',
            name='video_3_uploaded',
            field=models.FileField(blank=True, null=True, upload_to='language_barrier/videos/3/'),
        ),
        migrations.AddField(
            model_name='languagebarrierpage',
            name='video_3_youtube_url',
            field=models.URLField(blank=True, default='', help_text='YouTube video URL for right button'),
        ),
        migrations.AlterField(
            model_name='careercapsulespage',
            name='title',
            field=models.CharField(default='From Zero to Industry Ready', max_length=200),
        ),
        migrations.AlterField(
            model_name='careerroadmappage',
            name='title',
            field=models.CharField(default='IT Aspirant', max_length=200),
        ),
        migrations.AlterField(
            model_name='languagebarrierpage',
            name='title',
            field=models.CharField(default='3 Career Paths', max_length=200),
        ),
        migrations.AlterField(
            model_name='learningsystempage',
            name='title',
            field=models.CharField(default='30 Minutes a day', max_length=200),
        ),
        migrations.AlterField(
            model_name='skilltestpage',
            name='title',
            field=models.CharField(default='Conceptual Communication', max_length=200),
        ),
    ]
