# Generated by Django 4.2.30 on 2026-04-21 11:43

from django.db import migrations

def populate_initial_data(apps, schema_editor):
    HeroImage = apps.get_model('website', 'HeroImage')
    TopBanner = apps.get_model('website', 'TopBanner')
    HomeVideo = apps.get_model('website', 'HomeVideo')
    AIAdvantagePage = apps.get_model('website', 'AIAdvantagePage')
    SkillTestPage = apps.get_model('website', 'SkillTestPage')
    CareerRoadmapPage = apps.get_model('website', 'CareerRoadmapPage')
    CareerCapsulesPage = apps.get_model('website', 'CareerCapsulesPage')
    LearningSystemPage = apps.get_model('website', 'LearningSystemPage')
    LanguageBarrierPage = apps.get_model('website', 'LanguageBarrierPage')
    ReadyForTestPage = apps.get_model('website', 'ReadyForTestPage')
    TestBeforeTrustPage = apps.get_model('website', 'TestBeforeTrustPage')

    # HeroImage
    HeroImage.objects.create(
        image='hero/1.Hero_Image.png',
        active=True
    )

    # TopBanner
    TopBanner.objects.create(
        image='banner/Top_Banner.png',
        active=True
    )

    # HomeVideo
    HomeVideo.objects.create(
        title='Homepage Video',
        thumbnail='video_thumbnails/RAV_home_page_video_thumbnail.png',
        video_type='upload',
        uploaded_video='homepage_videos/video_20250325_135431.mp4',
        active=True
    )

    # AIAdvantagePage
    AIAdvantagePage.objects.create(
        image='ai_advantage/AI_fear_and_AI_adavntage__image.png',
        video_thumbnail='ai_advantage/thumbnails/AI_fear_and_AI_adavntage__thubnail.png',
        video_type='youtube',
        youtube_url='',
        active=True
    )

    # SkillTestPage
    SkillTestPage.objects.create(
        video_thumbnail='skill_test/thumbnails/Skill_Test_Thumbnail.png',
        video_type='youtube',
        youtube_url='',
        active=True
    )

    # CareerRoadmapPage
    CareerRoadmapPage.objects.create(
        image='career_roadmap/Career_Roadmap_Image.png',
        video_thumbnail='career_roadmap/thumbnails/Career_Roadmap_Thumbnail.png',
        video_type='youtube',
        youtube_url='',
        active=True
    )

    # CareerCapsulesPage
    CareerCapsulesPage.objects.create(
        image='career_capsules/30-Minute_Career_Capsules_Image.png',
        video_thumbnail='career_capsules/thumbnails/30-Minute_Career_Capsules_Thumbnail.png',
        video_type='youtube',
        youtube_url='',
        active=True
    )

    # LearningSystemPage
    LearningSystemPage.objects.create(
        image='learning_system/Learning_System_Image.png',
        video_thumbnail='learning_system/thumbnails/Learning_System_Thumbnail.png',
        video_type='youtube',
        youtube_url='',
        active=True
    )

    # LanguageBarrierPage
    LanguageBarrierPage.objects.create(
        background_image='language_barrier/Language_Barrier_image.png',
        video_1_uploaded='language_barrier/videos/1/VID-20250803-WA0203.mp4',
        video_1_type='upload',
        video_1_title='Left Video',
        video_2_uploaded='language_barrier/videos/2/VID-20250526-WA0017.mp4',
        video_2_type='upload',
        video_2_title='Center Video',
        video_3_uploaded='language_barrier/videos/3/VID-20250621-WA0021.mp4',
        video_3_type='upload',
        video_3_title='Right Video',
        active=True
    )

    # ReadyForTestPage
    ReadyForTestPage.objects.create(
        video_thumbnail='ready_for_test/thumbnails/slide2.png',
        video_type='upload',
        uploaded_video='homepage_videos/video_20250325_135431.mp4',
        active=True
    )

    # TestBeforeTrustPage
    TestBeforeTrustPage.objects.create(
        background_image='test_before_trust/background/slide3.png',
        video_1_uploaded='test_before_trust/videos/1/VID-20250518-WA0162.mp4',
        video_1_type='upload',
        video_1_title='Left Video',
        video_2_uploaded='test_before_trust/videos/2/VID-20240706-WA0000.mp4',
        video_2_type='upload',
        video_2_title='Center Video',
        video_3_uploaded='test_before_trust/videos/3/VID20250102125106.mp4',
        video_3_type='upload',
        video_3_title='Right Video',
        active=True
    )

class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_heroimage_readyfortestpage_testbeforetrustpage_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_initial_data, migrations.RunPython.noop),
    ]
