# Generated by Django 4.2.30 on 2026-04-21 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_populate_initial_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReadyForTestPage',
        ),
        migrations.DeleteModel(
            name='TestBeforeTrustPage',
        ),
        migrations.DeleteModel(
            name='TopBanner',
        ),
        migrations.RemoveField(
            model_name='languagebarrierpage',
            name='background_image',
        ),
        migrations.RemoveField(
            model_name='languagebarrierpage',
            name='video_1_title',
        ),
        migrations.RemoveField(
            model_name='languagebarrierpage',
            name='video_1_type',
        ),
        migrations.RemoveField(
            model_name='languagebarrierpage',
            name='video_1_uploaded',
        ),
        migrations.RemoveField(
            model_name='languagebarrierpage',
            name='video_1_youtube_url',
        ),
        migrations.RemoveField(
            model_name='languagebarrierpage',
            name='video_2_title',
        ),
        migrations.RemoveField(
            model_name='languagebarrierpage',
            name='video_2_type',
        ),
        migrations.RemoveField(
            model_name='languagebarrierpage',
            name='video_2_uploaded',
        ),
        migrations.RemoveField(
            model_name='languagebarrierpage',
            name='video_2_youtube_url',
        ),
        migrations.RemoveField(
            model_name='languagebarrierpage',
            name='video_3_title',
        ),
        migrations.RemoveField(
            model_name='languagebarrierpage',
            name='video_3_type',
        ),
        migrations.RemoveField(
            model_name='languagebarrierpage',
            name='video_3_uploaded',
        ),
        migrations.RemoveField(
            model_name='languagebarrierpage',
            name='video_3_youtube_url',
        ),
        migrations.AddField(
            model_name='languagebarrierpage',
            name='image',
            field=models.ImageField(help_text='Main image for the Language Barrier section', null=True, upload_to='language_barrier/'),
        ),
        migrations.AddField(
            model_name='languagebarrierpage',
            name='uploaded_video',
            field=models.FileField(blank=True, help_text='Upload video file if not using YouTube', null=True, upload_to='language_barrier/videos/'),
        ),
        migrations.AddField(
            model_name='languagebarrierpage',
            name='video_thumbnail',
            field=models.ImageField(help_text='Video thumbnail image', null=True, upload_to='language_barrier/thumbnails/'),
        ),
        migrations.AddField(
            model_name='languagebarrierpage',
            name='video_title',
            field=models.CharField(default='Watch Now', max_length=200),
        ),
        migrations.AddField(
            model_name='languagebarrierpage',
            name='video_type',
            field=models.CharField(choices=[('youtube', 'YouTube Link'), ('upload', 'Upload Video')], default='youtube', max_length=10),
        ),
        migrations.AddField(
            model_name='languagebarrierpage',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='YouTube video URL'),
        ),
        migrations.AddField(
            model_name='skilltestpage',
            name='image',
            field=models.ImageField(help_text='Main image for the Skill Test section', null=True, upload_to='skill_test/'),
        ),
    ]
