# Generated by Django 4.2.30 on 2026-04-22 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_languagebarrierpage_career_videos'),
    ]

    operations = [
        migrations.AddField(
            model_name='testbeforetrustpage',
            name='uploaded_video_1',
            field=models.FileField(blank=True, help_text='Upload video file for left button', null=True, upload_to='test_before_trust/videos/'),
        ),
        migrations.AddField(
            model_name='testbeforetrustpage',
            name='uploaded_video_2',
            field=models.FileField(blank=True, help_text='Upload video file for center button', null=True, upload_to='test_before_trust/videos/'),
        ),
        migrations.AddField(
            model_name='testbeforetrustpage',
            name='uploaded_video_3',
            field=models.FileField(blank=True, help_text='Upload video file for right button', null=True, upload_to='test_before_trust/videos/'),
        ),
        migrations.AddField(
            model_name='testbeforetrustpage',
            name='youtube_url_1',
            field=models.URLField(blank=True, help_text='YouTube video URL for left button'),
        ),
        migrations.AddField(
            model_name='testbeforetrustpage',
            name='youtube_url_2',
            field=models.URLField(blank=True, help_text='YouTube video URL for center button'),
        ),
        migrations.AddField(
            model_name='testbeforetrustpage',
            name='youtube_url_3',
            field=models.URLField(blank=True, help_text='YouTube video URL for right button'),
        ),
    ]
