# Generated by Django 4.2.30 on 2026-04-28 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_add_the_system_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroimage',
            name='button_text',
            field=models.CharField(default='▶ Start with a 5-minute overview of what this system delivers', max_length=200),
        ),
        migrations.AddField(
            model_name='heroimage',
            name='main_heading',
            field=models.CharField(default='Ekalavya Mission: From Zer0 to Industry-Ready — a Complete Transformation.', max_length=300),
        ),
        migrations.AddField(
            model_name='heroimage',
            name='subtitle',
            field=models.CharField(default='👉 Discover the All-in-One Skillset through a single, structured System before you Start.', max_length=300),
        ),
    ]
