# Generated by Django 4.2.30 on 2026-04-28 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_heroimage_button_text_heroimage_main_heading_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homevideo',
            name='line_1',
            field=models.CharField(default='👉 Industry-ready Training is different from Exam-ready Learning.', help_text='First highlight line below the video', max_length=300),
        ),
        migrations.AddField(
            model_name='homevideo',
            name='line_2',
            field=models.CharField(default='👉 The WINdianized Organic Learning System is built exactly for that transformation.', help_text='Second highlight line below the video', max_length=300),
        ),
    ]
