# Generated by Django 4.2.30 on 2026-04-28 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_homevideo_line_1_homevideo_line_2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homevideo',
            name='line_1',
        ),
        migrations.RemoveField(
            model_name='homevideo',
            name='line_2',
        ),
        migrations.AddField(
            model_name='thesystempage',
            name='highlight_1',
            field=models.CharField(default='👉 Industry-ready Training is different from Exam-ready Learning.', help_text='First highlight line in the description card', max_length=300),
        ),
        migrations.AddField(
            model_name='thesystempage',
            name='highlight_2',
            field=models.CharField(default='👉 The WINdianized Organic Learning System is built exactly for that transformation.', help_text='Second highlight line in the description card', max_length=300),
        ),
    ]
