# Generated by Django 4.2.30 on 2026-04-28 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_remove_homevideo_line_1_remove_homevideo_line_2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thesystempage',
            name='description',
        ),
        migrations.RemoveField(
            model_name='thesystempage',
            name='subtitle',
        ),
    ]
