# Generated by Django 4.2.30 on 2026-04-28 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_remove_aiadvantagepage_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skilltestpage',
            name='description',
        ),
        migrations.RemoveField(
            model_name='skilltestpage',
            name='subtitle',
        ),
        migrations.AddField(
            model_name='skilltestpage',
            name='line_1',
            field=models.CharField(default='👉 First highlight line for skill test section', help_text='First highlight line in the description card', max_length=300),
        ),
        migrations.AddField(
            model_name='skilltestpage',
            name='line_2',
            field=models.CharField(default='👉 Second highlight line for skill test section', help_text='Second highlight line in the description card', max_length=300),
        ),
    ]
