# Generated by Django 4.2.30 on 2026-04-28 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_remove_skilltestpage_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skilltestpage',
            name='subtitle',
            field=models.CharField(default='Test your skills and knowledge', help_text='Short subtitle shown in the card box', max_length=300),
        ),
    ]
