# Generated by Django 4.2.30 on 2026-04-28 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_skilltestpage_subtitle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skilltestpage',
            name='subtitle',
        ),
        migrations.AddField(
            model_name='skilltestpage',
            name='text',
            field=models.CharField(default='Test your skills and knowledge', help_text='Text shown above highlight lines in the card box', max_length=300),
        ),
    ]
