# Generated by Django 4.2.30 on 2026-04-28 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_remove_skilltestpage_subtitle_skilltestpage_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skilltestpage',
            name='text',
        ),
        migrations.AddField(
            model_name='skilltestpage',
            name='line_3',
            field=models.CharField(default='👉 Third highlight line for skill test section', help_text='Third highlight line in the card box', max_length=300),
        ),
        migrations.AlterField(
            model_name='skilltestpage',
            name='line_1',
            field=models.CharField(default='👉 First highlight line for skill test section', help_text='First highlight line in the card box', max_length=300),
        ),
        migrations.AlterField(
            model_name='skilltestpage',
            name='line_2',
            field=models.CharField(default='👉 Second highlight line for skill test section', help_text='Second highlight line in the card box', max_length=300),
        ),
    ]
