# Generated by Django 4.2.30 on 2026-04-28 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0025_remove_skilltestpage_text_skilltestpage_line_3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningsystempage',
            name='description',
        ),
        migrations.RemoveField(
            model_name='learningsystempage',
            name='subtitle',
        ),
        migrations.AddField(
            model_name='learningsystempage',
            name='line_1',
            field=models.CharField(default='👉 First highlight line for Learning System section', help_text='First highlight line in the card box', max_length=300),
        ),
        migrations.AddField(
            model_name='learningsystempage',
            name='line_2',
            field=models.CharField(default='👉 Second highlight line for Learning System section', help_text='Second highlight line in the card box', max_length=300),
        ),
        migrations.AddField(
            model_name='learningsystempage',
            name='line_3',
            field=models.CharField(default='👉 Third highlight line for Learning System section', help_text='Third highlight line in the card box', max_length=300),
        ),
    ]
