# Generated by Django 4.2.30 on 2026-04-28 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0027_remove_careerroadmappage_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readyfortestpage',
            name='description',
        ),
        migrations.RemoveField(
            model_name='readyfortestpage',
            name='subtitle',
        ),
        migrations.AddField(
            model_name='readyfortestpage',
            name='line_1',
            field=models.CharField(default='👉 First highlight line for Ready for Test section', help_text='First highlight line in the card box', max_length=300),
        ),
        migrations.AddField(
            model_name='readyfortestpage',
            name='line_2',
            field=models.CharField(default='👉 Second highlight line for Ready for Test section', help_text='Second highlight line in the card box', max_length=300),
        ),
        migrations.AddField(
            model_name='readyfortestpage',
            name='line_3',
            field=models.CharField(default='👉 Third highlight line for Ready for Test section', help_text='Third highlight line in the card box', max_length=300),
        ),
    ]
