# Generated by Django 4.2.30 on 2026-04-28 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0029_remove_careercapsulespage_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='languagebarrierpage',
            name='description',
        ),
        migrations.RemoveField(
            model_name='languagebarrierpage',
            name='subtitle',
        ),
        migrations.AddField(
            model_name='languagebarrierpage',
            name='line_1',
            field=models.CharField(default='👉 First highlight line for 3 Career Paths section', help_text='First highlight line in the card box', max_length=300),
        ),
        migrations.AddField(
            model_name='languagebarrierpage',
            name='line_2',
            field=models.CharField(default='👉 Second highlight line for 3 Career Paths section', help_text='Second highlight line in the card box', max_length=300),
        ),
        migrations.AddField(
            model_name='languagebarrierpage',
            name='line_3',
            field=models.CharField(default='👉 Third highlight line for 3 Career Paths section', help_text='Third highlight line in the card box', max_length=300),
        ),
        migrations.AddField(
            model_name='languagebarrierpage',
            name='line_4',
            field=models.CharField(default='👉 Fourth highlight line for 3 Career Paths section', help_text='Fourth highlight line in the card box', max_length=300),
        ),
        migrations.AddField(
            model_name='languagebarrierpage',
            name='line_5',
            field=models.CharField(default='👉 Fifth highlight line for 3 Career Paths section', help_text='Fifth highlight line in the card box', max_length=300),
        ),
        migrations.AddField(
            model_name='languagebarrierpage',
            name='line_6',
            field=models.CharField(default='👉 Sixth highlight line for 3 Career Paths section', help_text='Sixth highlight line in the card box', max_length=300),
        ),
    ]
