# Generated by Django 4.2.30 on 2026-04-28 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0030_remove_languagebarrierpage_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testbeforetrustpage',
            name='description',
        ),
        migrations.RemoveField(
            model_name='testbeforetrustpage',
            name='subtitle',
        ),
        migrations.AddField(
            model_name='testbeforetrustpage',
            name='line_1',
            field=models.CharField(default='👉 First highlight line for Test Before You Trust section', help_text='First highlight line in the card box', max_length=300),
        ),
        migrations.AddField(
            model_name='testbeforetrustpage',
            name='line_2',
            field=models.CharField(default='👉 Second highlight line for Test Before You Trust section', help_text='Second highlight line in the card box', max_length=300),
        ),
        migrations.AddField(
            model_name='testbeforetrustpage',
            name='line_3',
            field=models.CharField(default='👉 Third highlight line for Test Before You Trust section', help_text='Third highlight line in the card box', max_length=300),
        ),
        migrations.AddField(
            model_name='testbeforetrustpage',
            name='line_4',
            field=models.CharField(default='👉 Fourth highlight line for Test Before You Trust section', help_text='Fourth highlight line in the card box', max_length=300),
        ),
    ]
