# Generated by Django 4.2.30 on 2026-04-28 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0031_remove_testbeforetrustpage_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aiadvantagepage',
            name='subtitle',
        ),
    ]
