# Generated by safe rename refactor
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('website', '0032_remove_aiadvantagepage_subtitle'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SkillTestPage',
            new_name='ConceptualCommunication',
        ),
        migrations.RenameModel(
            old_name='LearningSystemPage',
            new_name='ThirtyMinutes',
        ),
        migrations.RenameModel(
            old_name='CareerRoadmapPage',
            new_name='ITAspirant',
        ),
        migrations.RenameModel(
            old_name='CareerCapsulesPage',
            new_name='ZeroToIndustry',
        ),
        migrations.RenameModel(
            old_name='LanguageBarrierPage',
            new_name='CareerPaths',
        ),
        migrations.RenameModel(
            old_name='TheSystemPage',
            new_name='TheSystem',
        ),
        migrations.RenameModel(
            old_name='AIAdvantagePage',
            new_name='AIAdvantage',
        ),
    ]
