# Generated by safe rename refactor
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('website', '0033_rename_models'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aiadvantage',
            old_name='line_1',
            new_name='highlight_1',
        ),
        migrations.RenameField(
            model_name='aiadvantage',
            old_name='line_2',
            new_name='highlight_2',
        ),
    ]
