# Generated by Django 4.2.30 on 2026-04-29 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0034_rename_aiadvantage_line_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aiadvantage',
            options={'verbose_name': '3)AI Advantage', 'verbose_name_plural': '3)AI Advantage'},
        ),
        migrations.AlterModelOptions(
            name='careerpaths',
            options={'verbose_name': '9)3 Career Paths', 'verbose_name_plural': '9)3 Career Paths'},
        ),
        migrations.AlterModelOptions(
            name='conceptualcommunication',
            options={'verbose_name': '4) Conceptual Communication', 'verbose_name_plural': '4) Conceptual Communication'},
        ),
        migrations.AlterModelOptions(
            name='homevideo',
            options={'verbose_name': '1) Home video', 'verbose_name_plural': '1) Home video'},
        ),
        migrations.AlterModelOptions(
            name='itaspirant',
            options={'verbose_name': '6) IT Aspirant', 'verbose_name_plural': '6) IT Aspirant'},
        ),
        migrations.AlterModelOptions(
            name='readyfortestpage',
            options={'verbose_name': '7)Ready for Test Page', 'verbose_name_plural': '7)Ready for Test Page'},
        ),
        migrations.AlterModelOptions(
            name='testbeforetrustpage',
            options={'verbose_name': '10)Test Before You Trust Page', 'verbose_name_plural': '10)Test Before You Trust Page'},
        ),
        migrations.AlterModelOptions(
            name='thesystem',
            options={'verbose_name': '2)The System', 'verbose_name_plural': '2)The System'},
        ),
        migrations.AlterModelOptions(
            name='thirtyminutes',
            options={'verbose_name': '5) 30Minutes', 'verbose_name_plural': '5) 30Minutes'},
        ),
        migrations.AlterModelOptions(
            name='zerotoindustry',
            options={'verbose_name': '8)Zero to Industry', 'verbose_name_plural': '8)Zero to Industry'},
        ),
        migrations.AddField(
            model_name='heroimage',
            name='secondary_subtitle',
            field=models.CharField(blank=True, default='Your Journey - Specially Designed for the AI Era.', help_text='Additional subtitle text displayed below the main subtitle in the hero section', max_length=300),
        ),
        migrations.AlterField(
            model_name='heroimage',
            name='main_heading',
            field=models.CharField(default='Ekalavya Mission: From Zer0 to Industry-Ready — a Complete Self-Transformation.', max_length=300),
        ),
        migrations.AlterField(
            model_name='heroimage',
            name='subtitle',
            field=models.CharField(default='👉 Discover the All-in-One Skillset through a Single, Structured System before you Start.', max_length=300),
        ),
    ]
