# Generated by Django 4.2.30 on 2026-04-29 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0035_alter_aiadvantage_options_alter_careerpaths_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='thesystem',
            name='highlight_3',
            field=models.CharField(blank=True, default='', help_text='Third highlight line in the description card (optional)', max_length=300),
        ),
    ]
