# Generated by Django 4.2.30 on 2026-04-29 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0036_thesystem_highlight_3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thesystem',
            name='highlight_3',
            field=models.CharField(blank=True, default='👉 Discover the Core Capabilities required for IT Industry-Readiness', help_text='Third highlight line in the description card (optional)', max_length=300),
        ),
    ]
