# Generated by Django 4.2.30 on 2026-04-29 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0037_alter_thesystem_highlight_3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thirtyminutes',
            name='line_3',
            field=models.CharField(default='👉 Introducing 30-minute - Bite-sized learning —Minimum one Focused Step a Day consistently.', help_text='Third highlight line in the card box', max_length=300),
        ),
    ]
