# Generated by Django 4.2.30 on 2026-04-29 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0038_alter_thirtyminutes_line_3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itaspirant',
            name='line_4',
            field=models.CharField(default='👉 Over 90% of Candidates fail in job interviews not due to lack of knowledge, but inability to express what they know.', help_text='Fourth highlight line in the card box', max_length=300),
        ),
    ]
