# Generated by Django 4.2.30 on 2026-05-01 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0039_alter_itaspirant_line_4'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroimage',
            name='button_text',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='heroimage',
            name='main_heading',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='heroimage',
            name='secondary_subtitle',
            field=models.CharField(blank=True, default='', help_text='Additional subtitle text displayed below the main subtitle in the hero section', max_length=300),
        ),
        migrations.AlterField(
            model_name='heroimage',
            name='subtitle',
            field=models.CharField(default='', max_length=300),
        ),
    ]
