# Generated by Django 4.2.30 on 2026-05-01 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0040_alter_heroimage_button_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heroimage',
            name='button_text',
        ),
        migrations.RemoveField(
            model_name='heroimage',
            name='main_heading',
        ),
        migrations.RemoveField(
            model_name='heroimage',
            name='secondary_subtitle',
        ),
        migrations.RemoveField(
            model_name='heroimage',
            name='subtitle',
        ),
        migrations.AddField(
            model_name='heroimage',
            name='hero_interstitial_image',
            field=models.ImageField(blank=True, help_text='Image to display between hero section and home video section', null=True, upload_to='hero/interstitial/'),
        ),
    ]
