# Generated by Django 4.2.30 on 2026-05-01 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0042_remove_aiadvantage_highlight_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='thesystem',
            name='header_image',
            field=models.ImageField(blank=True, help_text='Header image displayed above the video section', null=True, upload_to='the_system/'),
        ),
    ]
