# Generated by Django 4.2.30 on 2026-05-01 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0043_thesystem_header_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiadvantage',
            name='header_image',
            field=models.ImageField(blank=True, help_text='Header image displayed above the video section', null=True, upload_to='ai_advantage/'),
        ),
        migrations.AddField(
            model_name='careerpaths',
            name='header_image',
            field=models.ImageField(blank=True, help_text='Header image displayed above the video section', null=True, upload_to='career_paths/'),
        ),
        migrations.AddField(
            model_name='conceptualcommunication',
            name='header_image',
            field=models.ImageField(blank=True, help_text='Header image displayed above the video section', null=True, upload_to='conceptual_communication/'),
        ),
        migrations.AddField(
            model_name='itaspirant',
            name='header_image',
            field=models.ImageField(blank=True, help_text='Header image displayed above the video section', null=True, upload_to='it_aspirant/'),
        ),
        migrations.AddField(
            model_name='readyfortestpage',
            name='header_image',
            field=models.ImageField(blank=True, help_text='Header image displayed above the video section', null=True, upload_to='ready_for_test/'),
        ),
        migrations.AddField(
            model_name='testbeforetrustpage',
            name='header_image',
            field=models.ImageField(blank=True, help_text='Header image displayed above the video section', null=True, upload_to='test_before_trust/'),
        ),
        migrations.AddField(
            model_name='thirtyminutes',
            name='header_image',
            field=models.ImageField(blank=True, help_text='Header image displayed above the video section', null=True, upload_to='thirty_minutes/'),
        ),
        migrations.AddField(
            model_name='zerotoindustry',
            name='header_image',
            field=models.ImageField(blank=True, help_text='Header image displayed above the video section', null=True, upload_to='zero_to_industry/'),
        ),
    ]
