# Generated by Django 4.2.30 on 2026-05-01 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0044_aiadvantage_header_image_careerpaths_header_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homevideo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
