services:
  - type: web
    name: ekalavya
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn ekalavya.wsgi:application --bind 0.0.0.0:$PORT
    region: singapore
    plan: free